# Navigation.yml
main_navigation:
  - title: Home
    url: /pages/home
  - title: About
    url: /pages/about-us
  - title: Services
    url: /pages/services
  - title: Portfolio
    url: /pages/portfolio
    # children:
    #   - title: Web Development
    #     url: /services/web-development
    #   - title: SEO
    #     url: /services/seo
  - title: Contact
    url: /pages/contact